version: '3.5'

services:

  cx-traefik-forward-auth:
    build:
      context: .
      dockerfile: ./.docker/${ENVIRONMENT}.Dockerfile
      args:
        - node_env_type=${ENVIRONMENT}
    # platform: linux/amd64
    image: creoox/cx-traefik-forward-auth:${APP_VERSION}
    container_name: ${APP_NAME}-${APP_VERSION}
    env_file:
      - ./app/.env
    volumes:
      - /etc/localtime:/etc/localtime:ro            # Comment if using Windows
      # - ./app:/app                                # Uncomment for hot-reload, development only
      # - ./app/logs/error.log:/app/logs/error.log  # Uncomment for logs binding, production
    ports:
      - 80:${APP_PORT}
